services:
  db:
    image: postgres:16.3-alpine3.20
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - 'pgdata:/persisted_data/pgdata'
    networks:
      myapp_net:

volumes:
  pgdata:

networks:
  myapp_net:
